server:
  port: 8099
  tomcat:
    accept-count: 100 #the max number of buffer queue
    max-connections: 500 #the max number of connections
    max-threads: 100 #the max number of threads
spring:
  application:
    name: accserver
  redis:
    password:
    cluster:
      nodes: 192.168.217.128:7003,192.168.217.128:7004,192.168.217.132:7001,192.168.217.132:7002,192.168.217.133:7005,192.168.217.133:7006
      max-redirects: 6 #在集群情况下，一条redis命令执行时最多转发次数
    lettuce:
      pool:
        max-active: 1000 #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
datasource:
  #local or etcd
  initway: local
  #master slave dynamic
  qualifier: master

logging:
  config: classpath:log4j2.xml

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.yloonspring.accservers.po


nacos:
  config:
    server-addr: 192.168.217.132:8848
  discovery:
    server-addr: 192.168.217.132:8848
zookeeper:
  #开启标志
  enabled: true
  #服务器地址
  server: 192.168.217.132:2181,192.168.217.128:2181,192.168.217.133:2181
  #命名空间，被称为ZNode
  namespace: yloon
  #会话超时时间
  sessionTimeoutMs: 3000
  #连接超时时间
  connectionTimeoutMs: 60000
  #最大重试次数
  maxRetries: 2
  #初始休眠时间
  baseSleepTimeMs: 1000
dubbo:
  application:
    name: dubbo-provider
  registry:
    address: nacos://192.168.217.132:8848
  protocol:
    name: dubbo
    port: 20880
    host: 127.0.0.1
  scan:
    base-packages: com.yloonspring.accservers.dubboservice
mydubbo:
  service:
    version: 1.0.0
    name: dubboService